apiVersion: catalog.idp.io/v1alpha1
kind: SLO
metadata:
  name: checkout-latency
  namespace: demo-apps
spec:
  environmentRef:
    name: checkout-kind-dev-prod
  service: checkout-api
  objective: 99.5
  window: 30d
  indicator:
    type: latency
    metric: http_request_duration_seconds
    totalFilter: 'service="checkout-api"'
    latencyThreshold: "0.3"
  alerting:
    burnRates:
      - severity: critical
        shortWindow: 5m
        longWindow: 1h
        factor: 14.4
